theme: jekyll-theme-minimal

<html>
 <head>
  <title> Portfolio</title>
  <meta name="description" content="Como alterar a cor do plano de fundo de um site em HTML">
 </head>
 
 <body bgcolor="FF0000"> 
 </body>
 
</html>
