theme: jekyll-theme-minimal
title: Portfolio
image_path: ![linkedin](https://user-images.githubusercontent.com/60953136/113520109-1fe4ad00-954e-11eb-8621-b0819156fdf6.png)
feedback_email: fla_akira@hotmail.com
